new_client

diff --git a/client/docker/local/Dockerfile b/client/docker/local/Dockerfile
--- a/client/docker/local/Dockerfile
+++ b/client/docker/local/Dockerfile
@@ -7,11 +7,11 @@ RUN apk add --no-cache libc6-compat
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 
 RUN \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 FROM base as node-run-stage
 
@@ -23,7 +23,7 @@ COPY --from=node-build-stage /node_modules ./node_modules
 COPY . ${APP_HOME}
 
 RUN addgroup -g 1001 -S nodejs && \
-    adduser -S nextjs -u 1001 -G nodejs
+  adduser -S nextjs -u 1001 -G nodejs
 
 RUN chown -R nextjs:nodejs ${APP_HOME}
 
